version: "3.8"
services:
  backend:
    image: rdon11/project-backend:latest
    container_name: backend
    build: ./backend
    ports:
    - target: 5001
      published: 5001
  frontend:
    image: rdon11/project-frontend:latest
    container_name: frontend
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
    depends_on:
    - frontend 
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf

