version: "3.8"
services:
  database:
    image: rdon11/project-mysql:latest
    build: ./database
    container_name: mysql
    ports:
    - target: 3306
      published: 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - type: volume
      target: /var/lib/mysql
    deploy:
      replicas: 3
  backend:
    image: rdon11/project-backend:latest
    container_name: backend
    build: ./backend
    ports:
    - target: 5001
      published: 5001
    deploy:
      replicas: 3
  frontend:
    image: rdon11/project-frontend:latest
    container_name: frontend
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
    deploy:
      replicas: 3
  nginx:
    image: nginx:latest
    container_name: nginx
    deploy:
      replicas: 3
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf

